### ISSUE TITLE
Todo list :  Basic requirements for the bundle

### ISSUE THREAD

**Issue by sadortun** [DigitalState/Platform-Communication-Bundle#3]
Pending changes submited to #4 

# Allow to send a Communication
* [x] Perform the sending in the background
* [ ] Set Communication Read-only when sent
* [x] Add Communication Template and entityName selectors	
    - [x] Add Entity Selection field 
    - [x] Add List of Entity field selector

## Preparing a message
* [x] Add Entity Type selector, and variable selection for Template.  …			
* [x] Replace the Criteria/Criterion by ORO QueryFilter			
* [x] Remove Entity Variable selector			
* [x] Implemented QueryBuilder execution.  …			

## Generate Message
* [x]  Add a filter provider that can alter the `Message` before it's send to Transport
* [x]  Replace variables by values
* [x] Display pop-up preview for any recipient

## Transport
* [x] Add SparkPost Client API
* [x] Send a message using SparkPost
* [x] Store WebHooks when received from controller
* [x] Process WebHooks using a cron task

# Communications UI
- [x] Add List of Recipients Datagrid.		

![image](https://cloud.githubusercontent.com/assets/794449/21533378/cfea08c4-cd27-11e6-9d61-f8a925408bbd.png)

**Comment by sadortun** [comment]
A few recent improvements : 

# Overview
![image](https://cloud.githubusercontent.com/assets/794449/21966845/5b138e46-db49-11e6-9026-408220673765.png)


# Message preview 

![image](https://cloud.githubusercontent.com/assets/794449/21966865/b59ba664-db49-11e6-8ee4-64f674100e2e.png)


# Sending queue processing 

![image](https://cloud.githubusercontent.com/assets/794449/21966880/fe09a66c-db49-11e6-9c90-b9ce77abb864.png)

**Comment by StephenOTT** [comment]
@sadortun nice!
